apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 8.7.0
  nodeSets:
  - name: default
    count: 1
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 2
            limits:
              memory: 2Gi

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: elasticsearch
#  namespace: istio-system
#spec:
#  type: NodePort
#  ports:
#  - port: 9200
#    targetPort: 9200
#    nodePort: 32000
#  selector:
#    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
