apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.7.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=1024"
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 1.5Gi
            cpu: 1

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: kibana
#  namespace: istio-system
#spec:
#  ports:
#  - name: http
#    port: 5601
#    targetPort: 5601
#  selector:
#    k8s-app: kibana
#  type: NodePort
