apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Chart.Name }}
spec:
  selector:
    istio: ingressgateway # use Istio's default gateway implementation
  servers:
    {{- .Values.gateway.servers | toYaml | nindent 2 }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualservice.name }}
  namespace: {{ .Chart.Name }}
spec:
  hosts:
    {{- .Values.virtualservice.hosts | toYaml | nindent 2 }}
  gateways:
    {{- .Values.virtualservice.gateways | toYaml | nindent 2 }}
  http:
  - match:
    - uri:
        prefix: {{ ((index .Values.services 0)).prefix }}
    route:
    - destination:
        port:
          number: {{ ((index .Values.apps 0)).containerPort }}
        host: {{ printf "%s%s" ((index .Values.services 0)).name ".default.svc.cluster.local" }}  # destination hosts to which traffic is being sent. The hosts field applies to both HTTP and TCP services
  - match:
    - uri:
        prefix: {{ ((index .Values.services 1)).prefix }}
    route:
    - destination:
        port:
          number: {{ ((index .Values.apps 1)).containerPort }}
        host: {{ printf "%s%s" ((index .Values.services 1)).name ".default.svc.cluster.local" }}  # destination hosts to which traffic is being sent. The hosts field applies to both HTTP and TCP services
