apiVersion: v1
kind: Service
metadata:
  name: {{ ((index .Values.services 0)).name }}
  namespace: {{ .Chart.Name }}
spec:
  type: {{ ((index .Values.services 0)).type }}
  selector:
    app: {{ ((index .Values.apps 0)).name }}
  ports:
    {{- ((index .Values.services 0)).ports | toYaml | nindent 2 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ ((index .Values.services 1)).name }}
  namespace: {{ .Chart.Name }}
spec:
  type: {{ ((index .Values.services 1)).type }}
  selector:
    app: {{ ((index .Values.apps 1)).name }}
  ports:
    {{- ((index .Values.services 1)).ports | toYaml | nindent 2 }}
