apiVersion: v1
kind: Service
metadata:
  name: {{ ((index .Values.services 0)).name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ ((index .Values.services 0)).type }}
  selector:
    app: {{ ((index .Values.deployments 0)).name }}
  ports:
    {{- ((index .Values.services 0)).ports | toYaml | nindent 2 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ ((index .Values.services 1)).name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ ((index .Values.services 1)).type }}
  selector:
    app: {{ ((index .Values.deployments 1)).name }}
  ports:
    {{- ((index .Values.services 1)).ports | toYaml | nindent 2 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ ((index .Values.services 2)).name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ ((index .Values.services 2)).type }}
  selector:
    app: {{ ((index .Values.deployments 2)).name }}
  ports:
    {{- ((index .Values.services 2)).ports | toYaml | nindent 2 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ ((index .Values.services 3)).name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ ((index .Values.services 3)).type }}
  selector:
    app: {{ ((index .Values.deployments 3)).name }}
  ports:
    {{- ((index .Values.services 3)).ports | toYaml | nindent 2 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ ((index .Values.services 4)).name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ ((index .Values.services 4)).type }}
  selector:
    app: {{ ((index .Values.deployments 4)).name }}
  ports:
    {{- ((index .Values.services 4)).ports | toYaml | nindent 2 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ ((index .Values.services 5)).name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ ((index .Values.services 5)).type }}
  selector:
    app: {{ ((index .Values.deployments 5)).name }}
  ports:
    {{- ((index .Values.services 5)).ports | toYaml | nindent 2 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ ((index .Values.services 6)).name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ ((index .Values.services 6)).type }}
  selector:
    app: {{ ((index .Values.deployments 6)).name }}
  ports:
    {{- ((index .Values.services 6)).ports | toYaml | nindent 2 }}
